/**
 * Tile Grid Configuration
 * Generated by Tile Calibrator
 */

// Scale factor to fit tiles in game world (adjust to zoom in/out)
export const TILE_SCALE = 0.35;

export const TILE_CONFIG = {
  // Full tile dimensions (including depth edge) - scaled
  tileWidth: 183 * TILE_SCALE,
  tileHeight: 191 * TILE_SCALE,

  // Grid diamond dimensions (flat top face only) - scaled
  gridWidth: 183 * TILE_SCALE,
  gridHeight: 113 * TILE_SCALE,

  // Depth edge (3D effect) - scaled
  depthHeight: 78 * TILE_SCALE,

  // Grid offset (if tile isn't centered) - scaled
  gridOffsetY: -47 * TILE_SCALE,

  // Grid size
  cols: 10,
  rows: 10,
};

// Tile type constants
export const TILE = {
  GRASS: 0,
  COBBLE: 1,
  DIRT: 2,
};

// Map array: 0=grass, 1=cobble, 2=dirt
// Layout: 10 cols x 10 rows isometric grid
export const TILE_MAP = [
  //0  1  2  3  4  5  6  7  8  9
  [ 0, 0, 0, 0, 1, 1, 0, 0, 0, 0 ],  // Row 0
  [ 0, 0, 0, 1, 1, 1, 1, 0, 0, 0 ],  // Row 1
  [ 0, 0, 1, 1, 1, 1, 1, 1, 0, 0 ],  // Row 2
  [ 0, 1, 1, 1, 1, 1, 1, 1, 1, 0 ],  // Row 3
  [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],  // Row 4 - center
  [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ],  // Row 5 - center
  [ 0, 1, 1, 1, 1, 1, 1, 1, 1, 0 ],  // Row 6
  [ 0, 0, 1, 1, 1, 1, 1, 1, 0, 0 ],  // Row 7
  [ 0, 0, 0, 1, 1, 1, 1, 0, 0, 0 ],  // Row 8
  [ 0, 0, 0, 0, 1, 1, 0, 0, 0, 0 ],  // Row 9
];

// Building footprint size (2x2 tiles)
export const BUILDING_FOOTPRINT = 2;
